/**
 * Formula fixtures: `[expression, expected]`, evaluated against the row in
 * `formula.test.ts` with "now" at Sunday 2026-10-04 12:00 (local time).
 *
 * Expected values are normalized (see `norm` in the test): numbers rounded to 1e-9,
 * dates as `D:YYYY-MM-DD[THH:mm][→…]`, people as `P:name`, lists as arrays, and
 * `ERR` for an error while evaluating.
 */
export const CASES: [string, unknown][] = [
  // --- Text -----------------------------------------------------------------------
  ['"a" + "b"', 'ab'],
  ['"n=" + 4', 'n=4'],
  ['4 + "x"', '4x'],
  ['length("Notion")', 6],
  ['"Notion".length()', 6],
  ['length("")', 0],
  ['substring("Notion", 0, 3)', 'Not'],
  ['substring("Notion", 3)', 'ion'],
  ['"Notion".substring(1, 2)', 'o'],
  ['contains("Notion", "ion")', true],
  ['contains("Notion", "x")', false],
  ['test("Order #42", "\\\\d+")', true],
  ['test("abc", "^b")', false],
  ['match("a1b22c333", "\\\\d+")', ['1', '22', '333']],
  ['match("abc", "\\\\d")', []],
  ['replace("a-b-c", "-", "+")', 'a+b-c'],
  ['replaceAll("a-b-c", "-", "+")', 'a+b+c'],
  ['replaceAll("2026-10-04", "(\\\\d+)-(\\\\d+)-(\\\\d+)", "$3/$2/$1")', '04/10/2026'],
  ['lower("ABC")', 'abc'],
  ['upper("abc")', 'ABC'],
  ['"MiXeD".lower()', 'mixed'],
  ['trim("  a b  ")', 'a b'],
  ['repeat("ab", 3)', 'ababab'],
  ['repeat("x", 0)', ''],
  ['padStart("7", 3, "0")', '007'],
  ['padEnd("7", 3, "0")', '700'],
  ['padStart("1234", 3, "0")', '1234'],
  ['split("a,b,c", ",")', ['a', 'b', 'c']],
  ['split("abc", "")', ['a', 'b', 'c']],
  ['join(["a", "b"], "-")', 'a-b'],
  ['join([1, 2, 3], ", ")', '1, 2, 3'],
  ['format(42)', '42'],
  ['format(true)', 'true'],
  ['format(1.5)', '1.5'],
  ['format([1, "a", true])', '1, a, true'],
  ['toNumber("42")', 42],
  ['toNumber("3.5")', 3.5],
  ['toNumber("1,234")', 1234],
  ['toNumber(true)', 1],
  ['toNumber(false)', 0],
  ['toNumber("abc")', null],
  ['toNumber("  7 ")', 7],
  ['link("Notion", "https://notion.so")', 'Notion'],
  ['style("Hi", "b", "red")', 'Hi'],
  ['unstyle("Hi")', 'Hi'],
  ['concat("a", "b", "c")', 'abc'],
  ['"x".repeat(2) + "y"', 'xxy'],
  ['"Hello" == "Hello"', true],
  ['"a" != "b"', true],
  ['"apple" < "banana"', true],
  ['"item 9" < "item 10"', true],
  ['length(prop("Name"))', 11],
  ['upper(prop("Name"))', 'SERVO MOTOR'],
  ['prop("Name").split(" ")', ['Servo', 'motor']],
  ['trim(prop("Notes"))', 'Torque 13 kg·cm'],
  ['contains(prop("Notes"), "13")', true],
  ['match(prop("Notes"), "\\\\d+")', ['13']],
  ['prop("URL").replace("https://", "")', 'example.com'],
  ['substring(prop("Name"), 0, 5)', 'Servo'],
  ['"a\\"b"', 'a"b'],
  ["'single'", 'single'],
  ['"line\\nbreak".length()', 10],
  ['"café".length()', 4],
  ['“curly”', 'curly'],

  // --- Math -----------------------------------------------------------------------
  ['1 + 2', 3],
  ['7 - 10', -3],
  ['2 * 3 + 4', 10],
  ['2 + 3 * 4', 14],
  ['(2 + 3) * 4', 20],
  ['10 / 4', 2.5],
  ['7 % 3', 1],
  ['-7 % 3', -1],
  ['2 ^ 10', 1024],
  ['2 ^ 3 ^ 2', 512],
  ['-2 ^ 2', -4],
  ['0.1 + 0.2', 0.3],
  ['1 / 0', Infinity],
  ['add(1, 2)', 3],
  ['subtract(5, 2)', 3],
  ['multiply(2, 3)', 6],
  ['divide(6, 3)', 2],
  ['mod(7, 3)', 1],
  ['pow(2, 3)', 8],
  ['abs(-3)', 3],
  ['ceil(1.2)', 2],
  ['floor(1.8)', 1],
  ['floor(-1.2)', -2],
  ['round(1.5)', 2],
  ['round(1.234, 2)', 1.23],
  ['round(1234.5678, -2)', 1200],
  ['sqrt(16)', 4],
  ['cbrt(27)', 3],
  ['exp(0)', 1],
  ['ln(e())', 1],
  ['log10(1000)', 3],
  ['log2(8)', 3],
  ['sign(-4)', -1],
  ['sign(0)', 0],
  ['round(pi(), 4)', 3.1416],
  ['round(e(), 3)', 2.718],
  ['min(3, 1, 2)', 1],
  ['max(3, 1, 2)', 3],
  ['min([5, 2], 4)', 2],
  ['max([5, 2], 9)', 9],
  ['sum(1, 2, 3)', 6],
  ['sum([1, 2], [3, 4])', 10],
  ['mean([1, 2, 3, 4])', 2.5],
  ['median([3, 1, 2])', 2],
  ['median([4, 1, 2, 3])', 2.5],
  ['prop("Price") * prop("Qty")', 50],
  ['prop("Price") + 1', 13.5],
  ['prop("Empty") + 1', 1],
  ['empty(prop("Empty"))', true],
  ['round(prop("Price") / 3, 2)', 4.17],
  ['prop("Qty") > 3', true],
  ['prop("ID") * 10', 70],
  ['-prop("Qty")', -4],
  ['+5', 5],
  ['1e3', 1000],
  ['.5 + .5', 1],
  ['sum([])', 0],
  ['min([])', null],
  ['10 - 2 - 3', 5],
  ['100 / 10 / 2', 5],
  ['abs(prop("Qty") - 10)', 6],
  ['sqrt(-1)', null],
  ['2 * (3 + (4 - 1)) / 3', 4],
  ['prop("Price").round()', 13],
  ['(prop("Qty") + 1).pow(2)', 25],

  // --- Logic ----------------------------------------------------------------------
  ['true and false', false],
  ['true or false', true],
  ['true && true', true],
  ['false || false', false],
  ['not true', false],
  ['!false', true],
  ['not(true)', false],
  ['and(true, true, false)', false],
  ['or(false, false, true)', true],
  ['if(true, 1, 2)', 1],
  ['if(false, 1, 2)', 2],
  ['true ? "y" : "n"', 'y'],
  ['1 > 2 ? "a" : 2 > 1 ? "b" : "c"', 'b'],
  ['ifs(false, 1, true, 2, 3)', 2],
  ['ifs(false, 1, false, 2, 3)', 3],
  ['ifs(false, 1)', null],
  ['empty("")', true],
  ['empty(0)', true],
  ['empty([])', true],
  ['empty("a")', false],
  ['empty(false)', true],
  ['equal(1, 1)', true],
  ['unequal(1, 2)', true],
  ['larger(2, 1)', true],
  ['largerEq(2, 2)', true],
  ['smaller(1, 2)', true],
  ['smallerEq(3, 2)', false],
  ['1 == 1', true],
  ['1 != 1', false],
  ['[1, 2] == [1, 2]', true],
  ['[1, 2] == [2, 1]', false],
  ['1 < 2 and 2 < 3', true],
  ['prop("Done")', true],
  ['if(prop("Done"), "✅", "⏳")', '✅'],
  ['prop("Status") == "In progress"', true],
  ['not prop("Done")', false],
  ['prop("Done") and prop("Qty") > 2', true],
  ['ifs(prop("Price") > 100, "high", prop("Price") > 10, "mid", "low")', 'mid'],
  ['empty(prop("Tags"))', false],
  ['1 + 1 == 2', true],
  ['!(1 > 2)', true],
  ['true == false', false],
  ['let(x, 2, x * x)', 4],
  ['let(name, "Ada", "Hi " + name)', 'Hi Ada'],
  ['lets(a, 1, b, a + 1, a + b)', 3],
  ['lets(p, prop("Price"), q, prop("Qty"), p * q)', 50],
  ['let(x, 3, let(y, 4, x + y))', 7],
  ['false and 1 / 0 > 0', false],
  ['if(prop("Qty") >= 4, "enough", "order more")', 'enough'],
  ['prop("Empty") == prop("Empty")', true],
  ['empty(prop("Notes"))', false],

  // --- Dates ----------------------------------------------------------------------
  ['formatDate(now(), "YYYY-MM-DD")', '2026-10-04'],
  ['formatDate(now(), "HH:mm")', '12:00'],
  ['formatDate(today(), "YYYY-MM-DD HH:mm")', '2026-10-04 00:00'],
  ['formatDate(now(), "dddd")', 'Sunday'],
  ['formatDate(now(), "MMMM Do, YYYY")', 'October 4th, 2026'],
  ['formatDate(now(), "MMM D")', 'Oct 4'],
  ['formatDate(now(), "h:mm A")', '12:00 PM'],
  ['formatDate(now(), "[Week] W")', 'Week 40'],
  ['formatDate(now(), "Q")', '4'],
  ['formatDate(now(), "DDD")', '277'],
  ['formatDate(now(), "YY")', '26'],
  ['formatDate(now(), "ddd")', 'Sun'],
  ['formatDate(prop("Meeting"), "h:mm a")', '2:30 pm'],
  ['formatDate(parseDate("2026-10-01"), "Do")', '1st'],
  ['formatDate(parseDate("2026-10-02"), "Do")', '2nd'],
  ['formatDate(parseDate("2026-10-03"), "Do")', '3rd'],
  ['formatDate(parseDate("2026-10-11"), "Do")', '11th'],
  ['formatDate(parseDate("2026-10-22"), "Do")', '22nd'],
  ['day(now())', 7],
  ['day(parseDate("2026-10-05"))', 1],
  ['date(now())', 4],
  ['month(now())', 10],
  ['year(now())', 2026],
  ['hour(now())', 12],
  ['minute(now())', 0],
  ['week(now())', 40],
  ['week(parseDate("2026-01-05"))', 2],
  ['week(parseDate("2026-01-01"))', 1],
  ['hour(prop("Meeting"))', 14],
  ['minute(prop("Meeting"))', 30],
  ['formatDate(dateAdd(today(), 1, "days"), "YYYY-MM-DD")', '2026-10-05'],
  ['formatDate(dateAdd(today(), 2, "weeks"), "YYYY-MM-DD")', '2026-10-18'],
  ['formatDate(dateAdd(today(), 1, "months"), "YYYY-MM-DD")', '2026-11-04'],
  ['formatDate(dateAdd(parseDate("2026-01-31"), 1, "months"), "YYYY-MM-DD")', '2026-02-28'],
  ['formatDate(dateAdd(today(), 1, "years"), "YYYY-MM-DD")', '2027-10-04'],
  ['formatDate(dateAdd(today(), 1, "quarters"), "YYYY-MM-DD")', '2027-01-04'],
  ['formatDate(dateSubtract(today(), 4, "days"), "YYYY-MM-DD")', '2026-09-30'],
  ['formatDate(dateAdd(now(), 90, "minutes"), "HH:mm")', '13:30'],
  ['formatDate(dateAdd(now(), 3, "hours"), "HH:mm")', '15:00'],
  ['formatDate(dateAdd(today(), -1, "days"), "YYYY-MM-DD")', '2026-10-03'],
  ['formatDate(dateAdd(today(), 1, "day"), "YYYY-MM-DD")', '2026-10-05'],
  ['dateBetween(prop("Due"), today(), "days")', 16],
  ['dateBetween(today(), prop("Due"), "days")', -16],
  ['dateBetween(prop("Due"), today(), "weeks")', 2],
  ['dateBetween(parseDate("2026-12-01"), parseDate("2026-10-15"), "months")', 1],
  ['dateBetween(parseDate("2026-03-31"), parseDate("2026-02-28"), "months")', 1],
  ['dateBetween(parseDate("2027-10-04"), today(), "years")', 1],
  ['dateBetween(parseDate("2027-10-03"), today(), "years")', 0],
  ['dateBetween(now(), today(), "hours")', 12],
  ['dateBetween(now(), today(), "minutes")', 720],
  ['dateBetween(dateEnd(prop("Window")), dateStart(prop("Window")), "days")', 14],
  ['formatDate(dateStart(prop("Window")), "MMM D")', 'Oct 1'],
  ['formatDate(dateEnd(prop("Window")), "MMM D")', 'Oct 15'],
  ['formatDate(dateEnd(prop("Due")), "MMM D")', 'Oct 20'],
  ['prop("Due") > today()', true],
  ['prop("Due") < today()', false],
  ['today() == parseDate("2026-10-04")', true],
  ['timestamp(fromTimestamp(1000))', 1000],
  ['formatDate(fromTimestamp(timestamp(now())), "HH:mm")', '12:00'],
  ['formatDate(parseDate("2026-10-04T15:30"), "HH:mm")', '15:30'],
  ['parseDate("2026-02-29")', 'ERR'],
  ['parseDate("not a date")', 'ERR'],
  ['dateAdd(today(), 1, "fortnights")', 'ERR'],
  ['format(today())', 'October 4, 2026'],
  ['format(now())', 'October 4, 2026 12:00 PM'],
  ['format(prop("Window"))', 'October 1, 2026 → October 15, 2026'],
  ['formatDate(dateRange(today(), prop("Due")).dateEnd(), "MMM D")', 'Oct 20'],
  ['formatDate(prop("Created time"), "YYYY-MM-DD HH:mm")', '2026-10-01 09:00'],
  ['dateBetween(now(), prop("Created time"), "days")', 3],
  ['formatDate(parseDate("2026-10-04"), "D/M/YYYY")', '4/10/2026'],
  ['formatDate(parseDate("2026-03-05"), "DD.MM.YY")', '05.03.26'],
  ['formatDate(parseDate("2026-10-04"), "dd")', 'Su'],
  ['formatDate(parseDate("2026-10-04"), "d")', '0'],
  ['month(parseDate("2026-01-15"))', 1],
  ['day(parseDate("2026-10-11"))', 7],
  ['today()', 'D:2026-10-04'],
  ['now()', 'D:2026-10-04T12:00'],
  ['prop("Window")', 'D:2026-10-01→2026-10-15'],
  ['dateAdd(prop("Window"), 1, "days")', 'D:2026-10-02→2026-10-16'],
  ['dateRange(today(), prop("Due"))', 'D:2026-10-04→2026-10-20'],
  ['dateAdd(today(), 2, "hours")', 'D:2026-10-04T02:00'],
  ['parseDate("2026-10-04T08:15")', 'D:2026-10-04T08:15'],
  ['dateStart(prop("Due"))', 'D:2026-10-20'],
  ['month(prop("Empty date"))', null],
  ['formatDate(prop("Empty date"), "YYYY")', ''],

  // --- Lists ----------------------------------------------------------------------
  ['[1, 2, 3]', [1, 2, 3]],
  ['length([1, 2, 3])', 3],
  ['at([1, 2, 3], 0)', 1],
  ['at([1, 2, 3], -1)', 3],
  ['at([1, 2, 3], 5)', null],
  ['first([4, 5])', 4],
  ['last([4, 5])', 5],
  ['first([])', null],
  ['slice([1, 2, 3, 4], 1, 3)', [2, 3]],
  ['slice([1, 2, 3], 1)', [2, 3]],
  ['concat([1, 2], [3], [4, 5])', [1, 2, 3, 4, 5]],
  ['sort([3, 1, 2])', [1, 2, 3]],
  ['sort(["b", "a", "C"])', ['a', 'b', 'C']],
  ['sort([3, 1, 2], -current)', [3, 2, 1]],
  ['reverse([1, 2, 3])', [3, 2, 1]],
  ['includes([1, 2], 2)', true],
  ['includes(["a"], "b")', false],
  ['find([1, 5, 9], current > 3)', 5],
  ['find([1, 2], current > 5)', null],
  ['findIndex([1, 5, 9], current > 3)', 1],
  ['findIndex([1], current > 5)', -1],
  ['filter([1, 5, 9], current > 3)', [5, 9]],
  ['filter([1, 2, 3, 4], current % 2 == 0)', [2, 4]],
  ['some([1, 5], current > 3)', true],
  ['some([], current > 3)', false],
  ['every([4, 5], current > 3)', true],
  ['every([1, 5], current > 3)', false],
  ['map([1, 2, 3], current * 10)', [10, 20, 30]],
  ['map(["a", "b"], current + index)', ['a0', 'b1']],
  [
    'map([1, 2], [current, current])',
    [
      [1, 1],
      [2, 2],
    ],
  ],
  ['flat([[1], [2, 3]])', [1, 2, 3]],
  ['flat(map([1, 2], [current, current]))', [1, 1, 2, 2]],
  ['unique([1, 1, 2, 2, 3])', [1, 2, 3]],
  ['unique(["a", "b", "a"])', ['a', 'b']],
  ['[1, 2, 3].map(current ^ 2).sum()', 14],
  ['[3, 1, 2].sort().reverse().first()', 3],
  ['[1, 2, 3, 4].filter(current > 1).map(current * 2)', [4, 6, 8]],
  ['join(map([1, 2], format(current)), "+")', '1+2'],
  ['prop("Tags")', ['Actuator', 'Metal']],
  ['length(prop("Tags"))', 2],
  ['includes(prop("Tags"), "Metal")', true],
  ['prop("Tags").join(" & ")', 'Actuator & Metal'],
  ['prop("Tags").map(upper(current))', ['ACTUATOR', 'METAL']],
  ['prop("Tags").filter(current.contains("e"))', ['Metal']],
  ['prop("Tags").first()', 'Actuator'],
  ['contains(prop("Tags"), "Actuator")', true],
  ['[[1, 2], [3]].map(current.length())', [2, 1]],
  ['sum(map([1, 2, 3], current))', 6],
  ['[1, 2, 3].findIndex(current == 3)', 2],
  ['[].length()', 0],
  ['[1, "a"]', [1, 'a']],
  ['sort([parseDate("2026-10-05"), today()]).map(formatDate(current, "D"))', ['4', '5']],
  ['map([1, 2, 3], index)', [0, 1, 2]],
  ['map([[1, 2], [3]], current.map(current * 2))', [[2, 4], [6]]],
  ['filter(prop("Tags"), length(current) > 5)', ['Actuator']],
  ['prop("Files")', ['spec.pdf']],
  ['prop("Empty tags")', []],
  ['length(prop("Empty tags"))', 0],
  ['let(xs, [1, 2, 3], xs.map(current + xs.length()))', [4, 5, 6]],
  ['[1, 2, 3].some(current == 2) ? "has 2" : "no"', 'has 2'],
  ['unique(concat(prop("Tags"), ["Metal", "New"]))', ['Actuator', 'Metal', 'New']],

  // --- People and pages -----------------------------------------------------------
  ['name(prop("Created by"))', 'Ravi'],
  ['prop("Created by").name()', 'Ravi'],
  ['prop("Created by")', 'P:Ravi'],
  ['prop("Owner")', ['P:Ravi']],
  ['prop("Owner").map(current.name())', ['Ravi']],
  ['email(prop("Created by"))', ''],
  ['id()', 'row-1'],
  ['length(prop("Owner"))', 1],
  ['format(prop("Owner"))', 'Ravi'],
  ['"By " + prop("Created by").name()', 'By Ravi'],
  ['prop("Owner").map(current.name()).includes("Ravi")', true],

  // --- Comments, whitespace -------------------------------------------------------
  ['1 /* one */ + 2', 3],
  ['// a comment\n5', 5],
  ['  1\n  +\n  2  ', 3],
  ['if(\n  prop("Done"),\n  "yes", // done\n  "no"\n)', 'yes'],

  // --- Realistic formulas -----------------------------------------------------------
  [
    'prop("Done") ? "Complete" : dateBetween(prop("Due"), today(), "days") + " days left"',
    'Complete',
  ],
  ['if(prop("Due") < today(), "Overdue", formatDate(prop("Due"), "MMM D"))', 'Oct 20'],
  ['round(prop("Price") * prop("Qty") * 1.2, 2)', 60],
  ['"$" + format(prop("Price") * prop("Qty"))', '$50'],
  ['repeat("★", prop("Qty")) + repeat("☆", 5 - prop("Qty"))', '★★★★☆'],
  ['slice(prop("Name"), 0, 1)', 'ERR'],
  ['upper(substring(prop("Name"), 0, 1)) + substring(prop("Name"), 1)', 'Servo motor'],
  ['lets(total, prop("Price") * prop("Qty"), tax, total * 0.25, total + tax)', 62.5],
  ['prop("Tags").length() > 1 ? prop("Tags").join(", ") : "single"', 'Actuator, Metal'],
  ['dateBetween(dateEnd(prop("Window")), today(), "days") >= 0', true],
  ['formatDate(dateAdd(prop("Due"), 1, "months"), "MMMM")', 'November'],
  ['ifs(day(now()) >= 6, "weekend", "weekday")', 'weekend'],
  ['map(split("3,1,2", ","), toNumber(current)).sort()', [1, 2, 3]],
  ['padStart(format(prop("ID")), 4, "0")', '0007'],
  ['"TASK-" + padStart(format(prop("ID")), 3, "0")', 'TASK-007'],
  ['test(prop("URL"), "^https://")', true],
  ['replaceAll(lower(prop("Name")), " ", "-")', 'servo-motor'],
  ['week(prop("Due")) - week(today())', 3],
  ['year(prop("Due")) == year(now()) and month(prop("Due")) == month(now())', true],
  ['sum(prop("Tags").map(length(current)))', 13],
];
